version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/go/src/
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7
    container_name: mongodb-desafiotaghos
    restart: always
    ports:
      - '27017:27017'
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping')"]
      start_period: 0s
      interval: 500ms
      timeout: 5s
      retries: 5
