version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/go/src/
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7
    container_name: mongodb-desafiotaghos
    restart: always
    ports:
      - '27017:27017'
    command: mongod --replSet rs0
    healthcheck:
      test: |
        mongosh --eval "try { rs.status().ok } catch (e) { rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: 'localhost:27017' }] }).ok }"
      start_period: 0s
      interval: 500ms
      timeout: 5s
      retries: 5

volumes:
  mongodb1_data:
  mongodb2_data:
  mongodb3_data:
